let suggestion = [
    "Achari baingan",
    "Aloo gobi",
    "Aloo tikki",
    "Aloo tuk",
    "Aloo matar",
    "Aloo methi",
    "Aloo shimla mirch",
    "Amriti with rabdi",
    "Amritsari fish",
    "Amritsari kulcha",
    "Baati",
    "Bhatura",
    "Bhindi masala",
    "Biryani",
    "Butter chicken",
    "Chaat",
    "Chana masala",
    "Chapati",
    "Chicken razala",
    "Chicken Tikka",
    "Chicken Tikka masala",
    "Chole bhature",
    "Daal baati churma"	,
    "Daal puri",
    "Dal makhani",
    "Dal fara",
    "Dal",
    "Dal fry with tadka",
    "Dum aloo",
    "Poha",
    "Fara",
    "phirni",
    "French bean aloo",
    "Gajar ka halwa",
    "Gajar matar aloo",
    "Gobhi matar",
    "Imarti",
    "Hari mutter ka nimona",
    "Jalebi",
    "Jaleba",
    "Kachori",
    "Kadai paneer",
    "Kadhi pakoda",
    "Karela bharta",
    "Katha meetha petha",
    "kaddu halwa",
    "Kheer",
    "Khichdi",
    "Kadhi and Khichdi",
    "Kofta",
    "Kulfi falooda",
    "Laapsi",
    "Lauki ke kofte",
    "Lauki ki subji",
    "Litti chokha",
    "Makhaan ka kheer",
    "Makki di roti",
    "sarson da saag",
    "chaulai saab",
    "Methi saag",
    "Mathura ke pede",
    "Millet Halwa",
    "Misi roti",
    "Mixed vegetable",
    "Moong dal ka halwa",
    "Murgh musallam",
    "Mushroom do pyaza",
    "Mushroom matar",
    "Naan",
    "Navrattan korma",
    "Pakhala",
    "Palak paneer",
    "Paneer butter masala",
    "Paneer tikka masala",
    "Pani puri",
    "Panjeeri",
    "Papad",
    "Paratha",
    "Pattor",
    "Phirni",
    "Pindi chana",
    "Pinni",
    "Rajma chaval",
    "Rajma",
    "Ramatori subji",
    "Rongi",
    "Samosa",
    "Samose",
    "Sattu ki roti",
    "Shahi paneer",
    "Shahi tukra",
    "Singhada halwa",
    "Sooji halwa",
    "Sweet pethas",
    "kesar petha",
    "pista petha",
    "Vegetable jalfrezi",
    "Tandoori Chicken",
    "Tandoori Fish Tikka",
    "ananas menaskai",
    "Attu",
    "Aval kesari",
    "Halwa",
    "Bhajji",
    "Dosa",
    "Hyderabadi biryani",
    "Idli",
    "Indian omelette"	,
    "Masala Dosa",
    "Sambar",
    "Sevai",
    "Sponge dosa",
    "Uttapam",
    "Vada",
    "Barfi",
    "Chevdo",
    "Dabeli",
    "Dahi vada",
    "Dhokla",
    "Gajar halwa",
    "Gulab jamun",	
    "Gur",
    "Jalebi",
    "Jeera Aloo",
    "Laddu",
    "Malpua",
    "Chakri",
    "Patra",
    "Pav Bhaji",
    "Poori",
    "Shakarpara",
    "Namakpara",
    "Shrikhand",
    "Sohan papdi",
    "Ghevar",
    "Vada pav"
];